on:
  push:
    branches:
      - main

jobs:
  webpagetest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Run WebPageTest
      uses: WPO-Foundation/webpagetest-github-action@main
      with:
        apiKey: ${{ secrets.WPT_API_KEY }}
        urls: |
          https://lcan22.github.io/my-webpagetest-action/
          https://lcan22.github.io/my-webpagetest-action/about
        label: 'GitHub Action Test'